pipeline {
  agent none

  stages {
    stage('Back-end') {
      agent {
        docker {
          image 'maven:3.8.1-adoptopenjdk-11'
        }
      }
      steps {
        // Compile the project
        // Build the project
        sh 'mvn install'
        // Run tests
        sh 'mvn test'
        // Package the project
        sh 'mvn package'
        // Display Maven version
        sh 'mvn -version'
      }
    }
    
    stage('Front-end') {
      agent {
        docker {
          image 'node:16-alpine'
        }
      }
      steps {
        // Display npm version
        sh 'npm --version'
      }
    }
  }
}
